In [1]:
import numpy as np

In [2]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])

In [3]:
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [4]:
a = sampleArray[:,sampleArray[1,:].argsort()]

In [5]:
print("sorting numpy as rows: ")
a

sorting numpy as rows: 


array([[73, 43, 34],
       [12, 22, 82],
       [66, 94, 53]])

In [6]:
b = sampleArray[sampleArray[:,1].argsort()]

In [7]:
print("sorting numpy as colomn: ")
b

sorting numpy as colomn: 


array([[82, 22, 12],
       [34, 43, 73],
       [53, 94, 66]])