In [1]:
import numpy as np

In [2]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])

In [3]:
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [4]:
a = np.max(sampleArray,0)

In [5]:
print("amax from axis 0: ")
a

amax from axis 0: 


array([82, 94, 73])

In [6]:
b = np.min(sampleArray,1)

In [7]:
print('amin from axis 1: ')
b

amin from axis 1: 


array([34, 12, 53])